import { useState } from "react";
import DropZone from "./DropZone";
import DatabaseGrid from "./DatabaseGrid";
import { injectMeme } from "../api/client";

export default function SourcePanel({ memes, onMemeAdded }) {
  const [file, setFile] = useState(null);
  const [showDetails, setShowDetails] = useState(false);
  const [source, setSource] = useState("");
  const [community, setCommunity] = useState("");
  const [dateDetected, setDateDetected] = useState(
    new Date().toISOString().split("T")[0]
  );
  const [contextNotes, setContextNotes] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const canSubmit = file && !loading;

  const handleSubmit = async () => {
    if (!canSubmit) return;
    setLoading(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append("file", file);
      if (source.trim()) formData.append("source", source.trim());
      if (community.trim()) formData.append("community", community.trim());
      formData.append("date_detected", dateDetected);
      if (contextNotes.trim()) formData.append("context_notes", contextNotes.trim());

      await injectMeme(formData);
      setFile(null);
      setSource("");
      setCommunity("");
      setContextNotes("");
      setDateDetected(new Date().toISOString().split("T")[0]);
      onMemeAdded?.();
    } catch (err) {
      setError(err.response?.data?.detail || "Failed to inject meme");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full rounded-2xl border border-red-500/10 bg-red-500/2 p-5">
      <div className="flex items-center justify-between mb-5">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-white/70">
          Source Database
        </h2>
        <span className="inline-flex items-center rounded-full bg-red-500/10 px-2.5 py-1 text-xs font-semibold text-red-400 ring-1 ring-red-500/20">
          {memes?.length || 0} flagged
        </span>
      </div>

      <DropZone onFileSelect={setFile} accent="red" disabled={loading} />

      <button
        type="button"
        onClick={() => setShowDetails(!showDetails)}
        className="mt-3 flex items-center gap-1.5 text-xs text-white/30 hover:text-white/50 transition-colors self-start"
      >
        <svg
          className={`h-3 w-3 transition-transform ${showDetails ? "rotate-90" : ""}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
        </svg>
        {showDetails ? "Hide details" : "Add optional details (source, community...)"}
      </button>

      {showDetails && (
        <div className="mt-3 space-y-3 animate-fade-in-scale">
          <div>
            <label className="block text-xs text-white/40 mb-1">Source</label>
            <input
              type="text"
              value={source}
              onChange={(e) => setSource(e.target.value)}
              placeholder='e.g. "4chan /pol/" — defaults to "Scraped source"'
              className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white placeholder-white/20 focus:border-red-500/40 focus:outline-none transition-colors"
              disabled={loading}
            />
          </div>

          <div>
            <label className="block text-xs text-white/40 mb-1">Community / Group</label>
            <input
              type="text"
              value={community}
              onChange={(e) => setCommunity(e.target.value)}
              placeholder='e.g. "Siege Culture" — defaults to "Unclassified"'
              className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white placeholder-white/20 focus:border-red-500/40 focus:outline-none transition-colors"
              disabled={loading}
            />
          </div>

          <div>
            <label className="block text-xs text-white/40 mb-1">Date Detected</label>
            <input
              type="date"
              value={dateDetected}
              onChange={(e) => setDateDetected(e.target.value)}
              className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white focus:border-red-500/40 focus:outline-none transition-colors scheme-dark"
              disabled={loading}
            />
          </div>

          <div>
            <label className="block text-xs text-white/40 mb-1">Context Notes</label>
            <textarea
              value={contextNotes}
              onChange={(e) => setContextNotes(e.target.value)}
              placeholder="Auto-generated by AI if left blank"
              rows={2}
              className="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-white placeholder-white/20 focus:border-red-500/40 focus:outline-none transition-colors resize-none"
              disabled={loading}
            />
          </div>
        </div>
      )}

      {error && (
        <p className="mt-2 text-xs text-red-400">{error}</p>
      )}

      <button
        onClick={handleSubmit}
        disabled={!canSubmit}
        className="mt-4 w-full rounded-lg bg-red-600 px-4 py-2.5 text-sm font-semibold text-white transition-all hover:bg-red-500 disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2"
      >
        {loading ? (
          <>
            <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            Processing...
          </>
        ) : (
          "Add to Database"
        )}
      </button>

      <div className="flex-1 overflow-hidden mt-2">
        <DatabaseGrid memes={memes} />
      </div>
    </div>
  );
}
